INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('World Cleanup', 'Environmental', 40000, '10-12-2018', '10-12-2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Male Suicide Prevention', 'Health', 110000, '9-4-2019', '11-1-2021');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Endangered Species Rescue', 'Animals', 10000, '2-2-2017', '6-7-2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('7 Pieces', 'Environmental', 10000, '5-4-2019', '5-4-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('ChildWatch', 'Children', 25000, '12-12-2018', '12-12-2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Heart Attack Association', 'Health', 40000, '8-2-2018', '8-2-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Injured Athletes Association', 'Sports', 40000, '1-1-2018', '31-12-2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Ocean Clear', 'Environmental', 30000, '6-5-2018', '6-5-2020');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Homeless to Homefull', 'Homelessness', 55000, '4-7-2018', '12-31-2021');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Bushfire Relief', 'Environmental', 75000, '1-1-2017', '1-1-2019');

INSERT INTO users (name, age) VALUES ("Dave East", 31);
INSERT INTO users (name, age) VALUES ("Jay Z", 50);
INSERT INTO users (name, age) VALUES ("Terry Stork", 23);
INSERT INTO users (name, age) VALUES ("Eliza Do", 43);
INSERT INTO users (name, age) VALUES ("Rachel Dish", 33);
INSERT INTO users (name, age) VALUES ("Larry Bush", 25);
INSERT INTO users (name, age) VALUES ("Bernice Teal", 58);
INSERT INTO users (name, age) VALUES ("Earl Morris", 66);
INSERT INTO users (name, age) VALUES ("Graham Morris", 66);
INSERT INTO users (name, age) VALUES ("Darla Vera", 41);
INSERT INTO users (name, age) VALUES ("Nadine Yance", 21);
INSERT INTO users (name, age) VALUES ("Vaugh Cradle", 54);
INSERT INTO users (name, age) VALUES ("Barry Bonita", 32);
INSERT INTO users (name, age) VALUES ("Theo Marist", 55);
INSERT INTO users (name, age) VALUES ("Penelope Newman", 29);
INSERT INTO users (name, age) VALUES ("Darryl Gordeaux", 23);
INSERT INTO users (name, age) VALUES ("Trent Young", 20);
INSERT INTO users (name, age) VALUES ("Perry Winkle", 56);
INSERT INTO users (name, age) VALUES ("Harold Mawson", 34);
INSERT INTO users (name, age) VALUES ("Priya Doccio", 64);

INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 2, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 4, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1250, 7, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4000, 9, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (210, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 7, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (640, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (650, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (540, 8, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (225, 3, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (450, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (275, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (350, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (220, 4, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 9, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1200, 8, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5200, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (325, 3, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 2, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 5, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 6, 10);