INSERT INTO users (name, age) VALUES ('Adrian', 34);
INSERT INTO users (name, age) VALUES ('Len', 33);
INSERT INTO users (name, age) VALUES ('Aldo', 41);
INSERT INTO users (name, age) VALUES ('Anthony', 27);
INSERT INTO users (name, age) VALUES ('Alex', 33);
INSERT INTO users (name, age) VALUES ('Keith', 54);
INSERT INTO users (name, age) VALUES ('Wendy', 56);
INSERT INTO users (name, age) VALUES ('Max', 30);
INSERT INTO users (name, age) VALUES ('Darla', 25);
INSERT INTO users (name, age) VALUES ('Victor', 28);
INSERT INTO users (name, age) VALUES ('Rachel', 26);
INSERT INTO users (name, age) VALUES ('Lucy', 3);
INSERT INTO users (name, age) VALUES ('Leo', 1);
INSERT INTO users (name, age) VALUES ('Hermione', 8);
INSERT INTO users (name, age) VALUES ('Gucci', 9);
INSERT INTO users (name, age) VALUES ('Joseph', 20);
INSERT INTO users (name, age) VALUES ('Daniel', 19);
INSERT INTO users (name, age) VALUES ('Jim', 60);
INSERT INTO users (name, age) VALUES ('David', 35);
INSERT INTO users (name, age) VALUES ('Nick', 34);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pump Pro+", "Music", 2000000, "07/09/2009", "07/09/2025");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Bible Project", "Religion", 9000000, "01/10/1950", "02/14/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Magic Kingdom", "Recreation", 1000000000, "12/05/1901", "10/08/2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Goblins United", "Welfare", 200, "01/01/2010", "02/20/2051");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Crosstarfix", "Entertainment", 2500, "06/26/2006", "08/31/2041");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 06", "City", 10, "01/01/2010", "02/20/2016");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 07", "Urban", 1050, "01/01/2011", "02/20/2017");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 08", "Space", 104167, "01/01/2012", "02/20/2018");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 09", "Computing", 8675309, "01/01/2013", "02/20/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project 10", "Data", 10, "01/01/2014", "02/20/2020");

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2, 19, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3500, 11, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4651, 8, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5001, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800000, 6, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8675309, 2, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 18, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (420, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (350, 5, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12000, 2, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (240, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (36000, 9, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (121000, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (144, 12, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (350, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4651, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5001, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800000, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (8675309, 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 17, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (420, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (350, 4, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12000, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (240, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (36000, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (121000, 10, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (144, 11, 1);
